### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by kach** [areenberg/MDPSolver#6]
I get the following error when trying to import mdpsolver:

```
ImportError                               
Traceback (most recent call last)
Cell In[2], line 1
----> 1 import mdpsolver

File ~/lab/notebooks/venv/lib/python3.13/site-packages/mdpsolver/__init__.py:1
----> 1 from mdpsolver.model import model

File ~/lab/notebooks/venv/lib/python3.13/site-packages/mdpsolver/model.py:1
----> 1 from mdpsolver import solvermodule
      3 #auxilary methods
      4 from mdpsolver.problems.tbmaux import tbmaux

ImportError: cannot import name 'solvermodule' from partially initialized module 'mdpsolver' (most likely due to a circular import)
```

(Using Python 3.13.2 and pip 25.0.1.)

**Comment by areenberg** [comment]
Dear @kach 

Thank you for raising this issue!

The 'solvermodule' was not compatible with Python 3.13 (until now), which is likely the cause of the import error. If you run `pip install --upgrade mdpsolver` you should be able to import MDPSolver without problems.

Let me know if this works!

**Comment by kach** [comment]
Thanks for the quick response! Unfortunately, I get the same error after upgrading to v0.9.8…

**Comment by areenberg** [comment]
I am sorry to hear that. What operating system are you using? If you’re using Windows, did you install [Visual Studio 2022](https://visualstudio.microsoft.com/downloads/) (17.9) with the MSVC C++ compiler?

**Comment by kach** [comment]
Ah, I’m on macOS! Is that supported?

**Comment by areenberg** [comment]
I see! Unfortunately, MDPSolver is not supported on macOS. However, due to macOS's similarity with Ubuntu, you *might* be able to make it work by following [these steps](https://github.com/areenberg/MDPSolver/wiki#glibc-not-found).

I would be very interested in knowing if this works.

**Comment by kach** [comment]
Thanks! I think it would be easier for me to just find an Ubuntu machine…
